name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore solution
      run: dotnet restore lr4.slnx

    - name: Build solution
      run: dotnet build lr4.slnx --no-restore --configuration ${{ matrix.configuration }}

    - name: Run lr4.tests
      run: dotnet run --project lr4.tests/lr4.tests.csproj --configuration ${{ matrix.configuration }} --no-build
